### ISSUE TITLE
babel compile wouldn't copy files

### ISSUE THREAD

**Issue by hardfist** [kentcdodds/import-all.macro#12]
* `import-all.macro` version:2.0.3
* `node` version: 10.13.0
* `npm` (or `yarn`) version: 6.4.1

Relevant code or config

```javascript
// src/localize/index.js
import importAll from 'import-all.macro';
import path from 'path';
const dict = importAll.sync('./langs/*.json');
const locales = {};
for (const key of Object.keys(dict)) {
  const locale = path.basename(key).split('.')[0];
  locales[locale] = dict[key];
}
export default locales;

// src/localize/langs/
en.json
zh.json
cs.json
.....
```

What you did:

What happened:

It works fine when developing, but when i compile using babel, it wouldn't compile and copy files

Reproduction repository:

Problem description:

Suggested solution:

**Comment by kentcdodds** [comment]
Hi @hardfist,

Correct, you'll need to use the [`--copy-files`](https://babeljs.io/docs/en/babel-cli) flag or copy them yourself some other way. We can't really do anything for you here.
