### ISSUE TITLE
export-all.macro

### ISSUE THREAD

**Issue by lifeiscontent** [kentcdodds/import-all.macro#13]
What you did:

made https://github.com/lifeiscontent/export-all.macro

What happened:

tried to use this as a template, couldn't figure out how to publish

Reproduction repository:

https://github.com/lifeiscontent/export-all.macro

Problem description: I'd like to make an export-all.macro

Suggested solution: figure out what I need to change about kcd-scripts/.travis.yml to get it to deploy.

**Comment by kentcdodds** [comment]
Looking at the travis build log I saw this:

```
[release] semantic-release ERR! pre The GitHub user of the "GH_TOKEN" has not authenticated Travis CI yet. Go to https://travis-ci.com/, login with the GitHub user of this token and then restart this job.
```

My guess is if you do that then you can make it work.

Good luck.

**Comment by lifeiscontent** [comment]
@kentcdodds how do you generally bootstrap a project to inject the tokens into CI? I believe when you call `semantic-release-cli setup` it does it, but I'm not sure if the same hooks will run with `kcd-scripts`

**Comment by kentcdodds** [comment]
I use `semantic-release-cli setup`.

**Comment by lifeiscontent** [comment]
@kentcdodds sorry, last question. how in a macro can I check what is the current file I'm using the macro in? I think right here: https://github.com/lifeiscontent/export-all.macro/blob/551bfce73ddff831b78aba350926680080db0cac/src/macro.js#L34-L36

I should filter the list of exports if you're trying to export the file you're in.

e.g. if you have an index.js and you want to export all the files within that folder into index.js

**Comment by kentcdodds** [comment]
I think this is what you're looking for: https://github.com/lifeiscontent/export-all.macro/blob/551bfce73ddff831b78aba350926680080db0cac/src/macro.js#L26

**Comment by lifeiscontent** [comment]
Hey @kentcdodds, thanks for your help. I've been able to fix all the bugs in the code. I also updated travis with the tokens, but for some reason semantic release says there are no relevant changes to the code so it won't release a new version. Any ideas what this is about?

**Comment by kentcdodds** [comment]
Look at my manual-releases.md file in the `other` directory.
