### ISSUE TITLE
[feature suggestion] Ability to configure keys on returned object 

### ISSUE THREAD

**Issue by hrastnik** [kentcdodds/import-all.macro#14]
The current implementation of importAll.sync and importAll returns an object where the matched file paths are the keys and the value is set to all of the exports from the module.

I would like a way to specify the names of the keys on the object. For example a function could be used to modify the original key name like this. 

```
const utils = importAll.sync("../utils/*", ({ path }) =>  path.replace('../utils/', '').replace('.js', ''));

import * as _utilsAJs from '../utils/a.js'
import * as _utilsBJs from '../utils/b.js'
import * as _utilsCJs from '../utils/c.js'
import * as _utilsDJs from '../utils/d.js'

// Notice the keys are filenames without the paths and extensions
const a = {
  'a': _filesAJs, 
  'b': _filesBJs,
  'c': _filesCJs,
  'd': _filesDJs,
}
```

Additionally, other metadata could be passed to the function that defines the key names (like current file name, index of the matched file, etc)

**Comment by kentcdodds** [comment]
I worry this would make the tool more complex than is necessary. Is there any reason you couldn't just do that transformation at runtime?

**Comment by hrastnik** [comment]
I could do it in runtime. I just figured it could be done at build time to save a couple of bytes and processor cycles from the production build.

**Comment by kentcdodds** [comment]
I'm afraid the bytes and cycles saved wouldn't be worth the added complexity.

If you're really worried about it, them use preval.macro instead.

**Comment by kentcdodds** [comment]
Thanks for bringing up the idea!
