### ISSUE TITLE
[feature suggestion] Import default export when using importAll.sync 

### ISSUE THREAD

**Issue by hrastnik** [kentcdodds/import-all.macro#15]
When using importAll.sync the exported object doesn't include the default export from each of the matched modules.

It would be nice if the default export was available on the object. Perhaps something like this:

```
const routes = importAll.sync('../utils/*.js');

↓  ↓  ↓  ↓  ↓  

import __utilsAJsDefault, * as __utilsAJs from '../utils/a.js';
import __utilsBJsDefault, * as __utilsBJs from '../utils/b.js';
import __utilsCJsDefault, * as __utilsCJs from '../utils/c.js';

__utilsAJs.default = __utilsAJsDefault;
__utilsBJs.default = __utilsBJsDefault;
__utilsCJs.default = __utilsCJsDefault;

const routes = {
  '../utils/a.js': __utilsAJs,
  '../utils/b.js': __utilsBJs,
  '../utils/c.js': __utilsCJs,
}
```

**Comment by kentcdodds** [comment]
This is not correct. In the ESModules spec, the default value comes along when you use `import *`.

So:

```javascript
import * as __utilsAJs from '../utils/a.js'

__utilsAJs.default // <-- that is the default value
```

This has nothing to do with `import-all.macro`. It's working as-is 👍

**Comment by hrastnik** [comment]
Wow! This is news to me! But it's true.

There is surprisingly little information on what happens to the default export when using a namespaced import. I always assumed it doesn't get imported.

I'm sorry I wasted your time. But I'm glad at least I learned something in the process.
