### ISSUE TITLE
Cannot find module when build using babel cli

### ISSUE THREAD

**Issue by mamod** [kentcdodds/import-all.macro#18]
* `import-all.macro` version: latest
* `node` version: 6.7.0
* `npm` (or `yarn`) version: 11.10.0

Relevant code or config

```javascript
importAll('./files/*.{ts,tsx}').then((files) => {
    console.log(files)
})
```

What you did:

Using `import-all.macro` to load typescript and build using babel cli

What happened:

`import-all.macro` couldn't detect new transpiled ts files location when build using babel cli, this also happen to all transformed files that do not end with `.js` extension

Reproduction repository:

[mamod/import-all-repro](https://github.com/mamod/import-all-repro)

Problem description:

`import-all.macro` will not be able to detect typescript files if built using babel cli, while using bundlers like webpack/parcel... it will work just fine, the reason is that bundlers use file names map internally to resolve modules, babel will change files extension to `.js` of the transpiled files but `import-all.macro` will keep original globed file names to look them up.

Suggested solution:

Not sure if this is the best solution but I tried to fix this by omitting file extension for typescript files, you can check it at [mamod/import-all.macro](https://github.com/mamod/import-all.macro)

**Comment by kentcdodds** [comment]
Hi @mamod,

Are you saying that you're compiling your TS files as JS files right next to them? I don't think that's a super common practice and so I don't think we'll want to bake that into this macro. But you can definitely use your fork if it works for you :)

Thanks, and good luck :)

**Comment by mamod** [comment]
I'm not sure if I understand, do you mean mixing JS with TS files? if that's the case then 
I just updated my reproduction branch and now it doesn't include JS files at all, it was for demo purpose :)

but I guess you're right, this fix doesn't handle all possible cases, just for typescript and JSX, so maybe it's better if I use it right from my fork :)

Thank you for your time and for your great work :ok_hand:
