### ISSUE TITLE
Change the key used for imported files

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/import-all.macro#2]
- `import-all.macro` version: latest
- `node` version: latest
- `npm` (or `yarn`) version: latest

Relevant code or config:

```javascript
import importAll from 'import-all.macro'
const files = importAll.sync('./some-files/*/index.js')
```

Let's assume that `some-files` is a directory full of other directories each with an `index.js`. What's going to happen is it'll produce this:

```javascript
import _index from './some-files/a/index.js'
import _index2 from './some-files/b/index.js'

const files = {index: _index, index: _index2}
```

Suggested solution:

I'm thinking that the property name should be changed from the filename to the relative path. So it'd be:

```javascript
const files = {'./some-files/a/index.js': _index, './some-files/b/index.js': _index2}
```

I'd love to hear what folks think. cc @threepointone.

This would be a breaking change. I honestly foresaw this, but thought I could avoid it, but I've already bumped into it being annoying so 🤷‍♂️

**Comment by fatfisz** [comment]
Just had this problem, was very surprised :/

Wouldn't keeping the keys as paths relative to `opts.filename` of the processed file be ok? What is the rationale for the current behavior of shortening the keys?

**Comment by kentcdodds** [comment]
> What is the rationale for the current behavior of shortening the keys?

It was just me being dumb. I'll fix it up in a few hours. Unless you want to 😉

**Comment by fatfisz** [comment]
Sadly I've no time for this now, so it'd be awesome if you could :)

**Comment by fatfisz** [comment]
Actually nvm, I'm preparing the fix right now!
