### ISSUE TITLE
importAll as transform.

### ISSUE THREAD

**Issue by lifeiscontent** [kentcdodds/import-all.macro#8]
@kentcdodds first off, thanks for the badass macro.

One thing I was thinking about is using svgr and importAll.

e.g. using https://github.com/evenchange4/svgr.macro

and this together.

basically I'd like to be able to do something like this

import my svg files, transform them using svgr and output a const icons object which has the mapping of the component names so I can then create an Icon component which picks one from the `icons` by a `name` prop.

Is this currently possible? Or could we add this kind of transform function to import-all?

**Comment by kentcdodds** [comment]
That _might_ work... I'm not sure. Why don't you give it a try!

**Comment by lifeiscontent** [comment]
@kentcdodds actually, upon further review, svgr.macro has support for globs. so... I guess nevermind.

**Comment by lifeiscontent** [comment]
@kentcdodds but now using it, it's very very slow.

if I wanted to implement this functionality, would you recommend wrapping your import-all macro? or copying the source and modifying my needs for it?

This is my first time writing a macro, so any guidance would be much appreciated. I'm a core contributor to svgr so once I get some help, I'll add it into the core. 👍

**Comment by kentcdodds** [comment]
I'm guessing that any performance improvements you could make could be great contributions to svgr.macro :) I recommend filing an issue there.

**Comment by lifeiscontent** [comment]
@kentcdodds right, but I'm asking for some advice, would you recommend using the import-all macro as a dependency or copying the source from import-all and modifying it to the needs of the svgr macro?

Sorry, for the back and forth, just looking for some guidance.

**Comment by lifeiscontent** [comment]
the reason why I ask is because I'm not 100% clear on how the macros work internally, like, is it even possible to have another macro as a dependency?

**Comment by kentcdodds** [comment]
Gotcha, I'd recommend copying things over as needed :+1: This module is pretty small so sharing code would probably make things more complicated than necessary.

**Comment by lifeiscontent** [comment]
@kentcdodds ok, thanks for the info. Is there some documentation on how the internals of babel macros work? or best practices? like... if you shouldn't compose multiple macros together, etc. I know its still a fairly new concept so it'd make sense if something like that isn't available yet. Either way, thanks for creating such awesome projects ❤️

**Comment by kentcdodds** [comment]
Sure! I have a weekly newsletter and just last week my newsletter was about creating custom `babel-plugin-macros` macros :) [Read it here](https://buttondown.email/kentcdodds/archive/4b908555-ba5c-4c10-b491-411ad18fd4b9).

I also link to some videos and other material at the end there too. Good luck!
