### ISSUE TITLE
[Question] Import statement must be top, but this one is not necessary? (So Magic)

### ISSUE THREAD

**Issue by rockmandash** [kentcdodds/import-all.macro#9]
Thank you for this wonderful tool!
I have a question, I use this with create-react-app v2.
I discover I can do this!!!
```javascript
import importAll from 'import-all.macro';
let result
if (someCondition) {
  result = importAll.sync(`./someDir`);
} else {
  result = importAll.sync(`./otherDir`);
}
```
So weird it works!
Import statement must be top? Isn't it?
I google something like "conditional import in create-react-app", but result is dynamic import.
But `importAll.sync` is not dynamic import, how did all this work?

**Comment by kentcdodds** [comment]
I'm not sure exactly why or how it works, sorry.
